### ISSUE TITLE
Incorrect clues: Hint not directly deducible from the state of the puzzle (King left of Ampersand)

### ISSUE THREAD

**Issue by th122** [koro-xx/Watson#5]
I'm running into a number of clue-related issues on both MacOS and Windows. To keep things easier to track, I'll dump each sample into its own issue.

- [x]  MacOS:  0.8.3.1 binary  (watson-0.8.3b.bin-macOSX.zip, identifies as 0.8.1 in "About" ) 
- [ ]  Windows:  0.8.4b binary  (Watson.Installer.msi, identifies as 0.8.3 in "About" ) 

## King < Ampersand < Pi - Hint correct, but not directly deducible from the state of the puzzle and the clue quoted
The hint states "♔ left of &" as reasoning for ruling out the placement indicated. According to this clue, it could only rule out the king to the right of the one indicated.
If more clues are taken into consideration (& left of 𝝿), it is obviously correct to rule out that placement, just not from the clue that was quoted alone.

![Watson](https://user-images.githubusercontent.com/17241496/230775881-fa28a325-978f-499f-8a86-d9350b1736db.jpg)

## King < Ampersand < Pi, revealed
 
![Watson](https://user-images.githubusercontent.com/17241496/230778462-d243bf20-59a3-4dcf-9013-bdbdf90328fb.jpg)

**Comment by koro-xx** [comment]
I'm not quite understanding the issue. The clue system just provides a valid clue, maybe not chosen in the most "natural" way. The clue "♔ left of &" alone leads to the exclusion of the highlighted symbol because there are no & symbols in any column to the right of that one, therefore there is no way for the condition to be satisfied if the highlighted tile were to be placed there
(it is important that "left of" means "strictly left of", so ♔ and & in the same column does not satisfy the condition). I'm a bit groggy so I may be misinterpreting your point...

**Comment by th122** [comment]
It's not an error per se - the resulting situation is valid. I would have thought that given the clue I could safely discard the king in column 5. To discard the king in column 4 as suggested, I would need to use additional information (such as that ampersand is left of pi, and thus the king needs to shift accordingly).
I was under the impression that the hint system doesn't just disclose information, but applies the clues to the currently visible situation one by one, or barfs out an error if something was ruled out that is required by the solution. Maybe I misunderstood the hint system?

**Comment by th122** [comment]
Here's the save file in case it's of any help (certainly a lot less relevant than #7, which looks like an error to me)
[Watson.sav.gz](https://github.com/koro-xx/Watson/files/11186004/Watson.sav.gz)

**Comment by koro-xx** [comment]
The point here is that you can discard the king in *both* columns based only in the clue  "♔ left of &" . The hint system just chose the 4th column first instead of the 5th, but I bet if you ask for further hints after removing the 4th column king, you would get the hint to remove the 5th column one as well. 

Again, note that there are no & symbols in the 5th or 6th column, therefore the & must be in the 4th or lesser column. In any case, the 4th column cannot have the king, since it would be either in the same column as & or in a column to the right of &, both of which contradict that one clue.

I still fail to see how the other clue you mention is relevant.

**Comment by th122** [comment]
Going through this savegame again, I cannot reproduce my own reasoning, so I guess the fault is mine. Thanks for taking a look at it!
